### ISSUE TITLE
bug appears when running camdemo.py

### ISSUE THREAD

**Issue by guofengming11** [Zju-George/realtimeFER#1]
How to deal with it？
Thank you！
![报错1](https://user-images.githubusercontent.com/67827587/109626487-8fe0cb80-7b7b-11eb-8e40-68ee3b4bf2de.jpg)
![报错](https://user-images.githubusercontent.com/67827587/109626495-92dbbc00-7b7b-11eb-8b3d-231a27e2199c.jpg)

**Comment by sxhzju** [comment]
I have no clue what's wrong here since I don't know which variable is **None**.
 Is it `drawing_spec`? You can try printing the type of `drawing_spec` first.

**Comment by guofengming11** [comment]
> I have no clue what's wrong here since I don't know which variable is **None**.
> Is it `drawing_spec`? You can try printing the type of `drawing_spec` first.

print all of them 
Thank you！
![02](https://user-images.githubusercontent.com/67827587/109628833-29a97800-7b7e-11eb-9033-4acebe176145.jpg)
![03](https://user-images.githubusercontent.com/67827587/109628844-2c0bd200-7b7e-11eb-813c-2c203fbc671b.jpg)

**Comment by guofengming11** [comment]
The strange thing is that none of them are NONE

**Comment by sxhzju** [comment]
Oh! I remember that, I've changed the source code of mediapipe a little bit..
The original return type of function `mp_drawing.draw_landmarks`  is None, but I’ve changed the code to return the max&min pixel coordinate of the landmarks to make the crop..
Sorry about that, I will show the modified code of `draw_landmarks` later tonight!
Btw, thanks for reporting that error!

> The strange thing is that none of them are NONE

**Comment by guofengming11** [comment]
thank you for sharing！

**Comment by sxhzju** [comment]
> thank you for sharing！

Check out the updates.
In summary, just replace one source file in mediapipe.

**Comment by guofengming11** [comment]
What expression does ‘NF’ stand for?

**Comment by sxhzju** [comment]
> What expression does ‘NF’ stand for?

'Not a face'.
